---
name: Home Assistant Stream Deck
version: "2024.12.10"
slug: home-assistant-streamdeck-yaml
description: >
  This add-on allows you to control your Home Assistant
  instance via a Stream Deck, making it easier than ever to
  manage your smart home devices and scenes üè†. The add-on is highly
  customizable and configured using YAML files. It runs on the
  same machine as Home Assistant and supports Linux-based supervised
  Home Assistant installations. Check out the
  basnijholt/home-assistant-streamdeck-yaml GitHub repository
  (https://github.com/basnijholt/home-assistant-streamdeck-yaml) for
  more details. Also check out the add-on documentation
  (https://basnijholt.github.io/home-assistant-streamdeck-yaml-addon/) for
  add-on configuration details.
url: https://github.com/basnijholt/home-assistant-streamdeck-yaml-addon
hassio_api: true
homeassistant_api: true
host_network: true
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: 80
  443/tcp: 443
ports_description:
  80/tcp: home-assistant-streamdeck-yaml WebSocket port
  443/tcp: home-assistant-streamdeck-yaml WebSocket SSL port
usb: true
devices:
  - /dev/bus/usb
map:
  - config:rw
panel_icon: mdi:keyboard
options:
  streamdeck_config: ""
  websocket_protocol: ""
  hass_host: ""
  hass_token: ""
  streamdeck_dotenv: ""
schema:
  streamdeck_config: str?
  websocket_protocol: str?
  hass_host: str?
  hass_token: password?
  streamdeck_dotenv: str?
